spring:
  datasource:
    url: jdbc:mysql://192.168.254.100:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
logging:
  level:
    root: info
    com.endwas: debug
  file:
    name: log/blog-dev.log

mybatis:
  type-aliases-package: com.endwas.entity
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true


